In [2]:
"""Q1.Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables."""
import numpy as np

In [3]:
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [29]:
"""Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list."""
import numpy as np

In [30]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data types of elements in list_:")
for element in list_:
    print(type(element))
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [37]:
"""Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list."""

import numpy as np
num_list = [[ 1 , 2 , 3 ] , [ 4 , 5 , 6 ]]
num_array = np.array(object = num_list)

In [38]:
print("Data types of elements in num_list:")
for element in num_list:
    print(type(element))

print("Data types of elements in num_array:")
for element in num_array:
    print(type(element))


Data types of elements in num_list:
<class 'list'>
<class 'list'>
Data types of elements in num_array:
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [39]:
"""Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size"""
import numpy as np

In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr.size

8

In [12]:
arr.shape

(2, 4)

In [16]:
"""Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function"""
import numpy as np

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
"""Q6. Create an identity matrix of shape (5,5) using numpy functions?"""
import numpy as np

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])